
[env]
TERM = "xterm-256color"
XDG_CONFIG_HOME="/Users/arthurjordao/.config"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = """

&"""
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = """

c"""
key = "T"
mods = "Command"

[terminal.shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window.dimensions]
columns = 133
lines = 40

[general]
import = ["/Users/arthurjordao/.config/alacritty/themes/catppuccin-latte.toml"]

[terminal]
