import = ["/Users/arthurjordao/.config/alacritty/themes/catppuccin-latte.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = """

&"""
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = """

c"""
key = "T"
mods = "Command"

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[window.dimensions]
columns = 133
lines = 40
