cursor = '▇'
blinking-cursor = false
theme = "catppuccin-latte"

[window]
width = 1000
height = 700

[fonts]
size = 18
family = "FiraCode Nerd Font"

[shell]
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/opt/homebrew/bin/tmux"
