tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'bat'
brew 'exa'
brew 'gh'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'jq'
brew 'lazygit'
brew 'neovim'
brew 'python@3'
brew 'ripgrep'
brew 'tmux'
brew 'tree-sitter'
brew 'zsh'
brew 'zsh-completions'

cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
