#!/bin/sh

alias exall="exa -l --icons --git"
alias exal="exa -la --icons --git"
alias exa="exa --icons --git"
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'
alias ls="ls --color=auto"
alias ll="ls -l"
alias l="ls -la"
