#!/bin/sh

alias cat=bat
alias ll="exa -l --icons"
alias l="exa -la --icons"
alias ls="exa"
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'
