#!/bin/sh

. "$HOME/.cargo/env"

export GPG_TTY=$(tty)

export GOPATH=$HOME/go
export GOROOT="$(brew --prefix golang)/libexec"

export PATH=/opt/homebrew/bin:$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH:$HOME/.ghcup/bin:$HOME/.cache/rebar3/bin:${GOPATH}/bin:${GOROOT}/bin

export FZF_PREVIEW_ADVANCED=true

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

fpath+=($ZDOTDIR/plugins/pure)

[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" 

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
eval "$(direnv hook zsh)"

export EDITOR=nvim

HISTFILE=~/.config/zsh/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
