#!/bin/sh

. "$HOME/.cargo/env"

export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH:$HOME/.emacs.d/bin

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

export EDITOR=lvim

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

eval "$(direnv hook zsh)"

[ -f "/Users/$HOME/.ghcup/env" ] && source "/Users/$HOME/.ghcup/env" 
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"


fpath+=($ZDOTDIR/plugins/pure)
