#!/bin/sh

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_plugin "sindresorhus/pure"
zsh_add_plugin "unixorn/fzf-zsh-plugin"
zsh_add_plugin "Aloxaf/fzf-tab"
